### PR TITLE
feat: Add a section about code consistency

### LINKED ISSUE #1: Add a "code consistency" chapter
Code consistency is crucial for readability and maintainability:

- [ ] What is consistency?  (is it the look of the code? is it the structure?)
- [ ] What isn't consistency? (e.g. does using `class` and `function` declarations cause inconsistency?)
- [ ] Why consistency matters
- [ ] How consistency can bring about better development practices

Consistency patterns:

- revealing module pattern
- [more describe here](https://addyosmani.com/resources/essentialjsdesignpatterns/book/#designpatternsjavascript)

### PR DESCRIPTION
**Pull request by bebraw**
Closes #1.

CC @rstegg, @dcarral .

### CODE REVIEW

**Comment by sapegin** [comment]
This section is too abstract for me to be useful ;-|

**Comment by bebraw** [comment]
Ok, I'll add examples of consistency to get the point better. 👍

**Comment by bebraw** [comment]
I added a few examples and bridged the idea to those.

**Comment by sapegin** [comment]
It’s better now!

**Pull request merged**
